# This file is copied from https://github.com/kubernetes-sigs/cluster-api/blob/main/.golangci.yml, and removed some unrelated settings.
# TODO: refine this file
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace

linters-settings:
  ifshort:
    # Maximum length of variable declaration measured in number of characters, after which linter won't suggest using short syntax.
    max-decl-chars: 50
  importas:
    no-unaliased: true
  staticcheck:
    go: "1.17"
  stylecheck:
    go: "1.17"
  gosec:
    excludes:
      - G307 # Deferring unsafe method "Close" on type "\*os.File"
      - G108 # Profiling endpoint is automatically exposed on /debug/pprof
  gocritic:
    disabled-checks:
      - appendAssign

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # We are disabling default golangci exclusions because we want to help reviewers to focus on reviewing the most relevant
  # changes in PRs and avoid nitpicking.
  exclude-use-default: false
  exclude-rules:
    - linters:
        - revive
      text: "exported: exported method .*\\.(Reconcile|SetupWithManager|SetupWebhookWithManager) should have comment or be unexported"
    - linters:
        - errcheck
      text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    # Exclude some packages or code to require comments, for example test code, or fake clients.
    - linters:
        - revive
      text: exported (method|function|type|const) (.+) should have comment or be unexported
      source: (func|type).*Fake.*
    - linters:
        - revive
      text: exported (method|function|type|const) (.+) should have comment or be unexported
      path: fake_\.go
    - linters:
        - revive
      text: exported (method|function|type|const) (.+) should have comment or be unexported
      path: cmd/clusterctl/internal/test/providers.*.go
    - linters:
        - revive
      text: exported (method|function|type|const) (.+) should have comment or be unexported
      path: "(framework|e2e|infrastructure/docker)/.*.go"
    # Disable unparam "always receives" which might not be really
    # useful when building libraries.
    - linters:
        - unparam
      text: always receives
    # Dot imports for gomega or ginkgo are allowed
    # within test files.
    - path: _test\.go
      text: should not use dot imports
    - path: (framework|e2e)/.*.go
      text: should not use dot imports
    - path: _test\.go
      text: cyclomatic complexity
    # Append should be able to assign to a different var/slice.
    - linters:
        - gocritic
      text: "appendAssign: append result not assigned to the same slice"
    # ifshort flags variables that are only used in the if-statement even though there is
    # already a SimpleStmt being used in the if-statement in question.
    - linters:
        - ifshort
      text: "variable .* is only used in the if-statement"
      path: controllers/mdutil/util.go
    # Disable linters for conversion
    - linters:
        - staticcheck
      text: "SA1019: in.(.+) is deprecated"
      path: .*(api|types)\/.*\/conversion.*\.go$
    - linters:
        - revive
      text: exported (method|function|type|const) (.+) should have comment or be unexported
      path: .*(api|types)\/.*\/conversion.*\.go$
    - linters:
        - revive
      text: "var-naming: don't use underscores in Go names;"
      path: .*(api|types)\/.*\/conversion.*\.go$
    - linters:
        - revive
      text: "receiver-naming: receiver name"
      path: .*(api|types)\/.*\/conversion.*\.go$
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names;"
      path: .*(api|types)\/.*\/conversion.*\.go$
    - linters:
        - stylecheck
      text: "ST1016: methods on the same type should have the same receiver name"
      path: .*(api|types)\/.*\/conversion.*\.go$

run:
  timeout: 10m
  allow-parallel-runners: true
