linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - errcheck
  - exportloopref
  - goconst
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nakedret
  - nilerr
  - prealloc
  - revive
  - rowserrcheck
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - varcheck
  - whitespace

run:
  timeout: 30m
  allow-parallel-runners: true
