name: golangci-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - master
permissions:
  contents: read
jobs:
  golangci:
    strategy:
      matrix:
        go-version: []
        os: [macos-latest, ubuntu-latest ]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
